# Required
version: 0.0.1

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Optionally set the version of Python and requirements required to build your docs
python:
  version: 3.10
  install:
    - requirements: docs/requirements.txt
